services:
  caddy_proxy:
    build:
      context: caddy/.
    image: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - api
      - frontend


  cnn_api:
    build:
      context: api/.
    image: cnn_api
    expose:
      - "8000"
    restart: unless-stopped


  cnn_website:
    build:
      context: website/.
    image: cnn_website
    expose:
      - "8080"
    restart: unless-stopped