services:
  caddy_proxy:
    build:
      context: caddy/.
    image: caddy_proxy
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./caddy/data:/data/caddy
    depends_on:
      - cnn_api
      - cnn_website
    networks:
      - cnn_network
    pull_policy: never
    container_name: caddy_proxy


  cnn_api:
    build:
      context: api/.
    image: cnn_api
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - cnn_network
    pull_policy: never
    container_name: cnn_api
    volumes:
      - ./database:/database


  cnn_website:
    build:
      context: website/.
    image: cnn_website
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - cnn_network
    pull_policy: never
    container_name: cnn_website

networks:
  cnn_network:
    name: cnn_network