services:
  cnn_api:
    build:
      context: api/.
    image: cnn_api
    ports:
      - "8000:8000"
    restart: unless-stopped

  cnn_website:
    build:
      context: website/.
    image: cnn_website
    ports:
      - "8080:80"
    restart: unless-stopped

  caddy:
    build:
      context: caddy/.
    image: cnn_website
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped